### tampilkan semua user
GET http://localhost:8080/user

### tambah user
POST http://localhost:8080/user
Content-Type: application/json

{
    "username" : "ilhan@gmail.com",
    "email" : "ilhan@gmail.com",
    "password" : "123456"
}

### login
POST http://localhost:8080/user/login
Content-Type: application/json

{
    "email" : "muiz@gmail.com",
    "password" : "123456"
}

### logut
GET http://localhost:8080/user/logout 

### refresh-access-token
GET http://localhost:8080/user/refresh-access-token

###
GET http://localhost:8080/pelayanan/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjc5MDU4ODE4LCJleHAiOjE2NzkwNTg4Mzh9.vOrRukWy5vWNJSwdCyAyAKSaZgm3axYkdk8Mr9kLeyk

###
POST http://localhost:8080/pelayanan/
Content-Type :application/json

{
    "kritik" : "sinyal",
    "saran" : "bangun",
    "fk_user" : 1
}

###
DELETE http://localhost:8080/pelayanan/7




####################################################################################################
### tampiilkan semua kategori pengaduan
GET http://localhost:8080/kategori-pengaduan


### tambah kategori pengaduan
POST http://localhost:8080/kategori-pengaduan
Content-Type: application/json

{
    "nama" : "Jalan Rusak"
}



###
GET http://localhost:8080/gambar